### PR TITLE
Skip the failing dynamic vs static tests on Win32 in blead

### PR DESCRIPTION
**Pull request by toddr**
Work around for https://github.com/Perl/perl5/issues/17601

See also https://rt.cpan.org/Ticket/Display.html?id=115321

This mirror's @tonycoz 's merge to blead found here https://github.com/Perl/perl5/pull/18157

### CODE REVIEW

**Comment by karenetheridge** [comment]
It would be good to get to the bottom of these test issues, rather than disabling them.

**Comment by toddr** [comment]
I agree. However, RT-115321 has been open for 4 years now.

Also to Quote @tonycoz:

> %Config provides the information required, but the generated Makefile in this case is generated for LINKTYPE=static, but then run with LINKTYPE=dynamic for Linux that's not such a big deal, if perl is dynamic ccflags includes -fPIC as a matter of course, which just slows the resulting binary, but it is a problem on Win32 due to the way data imports work. I have trouble believing anyone is doing this in the wild ... it might be that the test just isn't practical on Win32, to make it work I think you'd have to use whatever conditional mechanisms the various Win32 makes support.

This has been causing noise on the smokers and I agree with him that turning the test off for a truly corner case like this makes sense until someone comes back and says: `I care about Perl running this way on Windows`. I am dubious that this will ever happen.

**Comment by Leont** [comment]
> It would be good to get to the bottom of these test issues, rather than disabling them.

I think it's understood well enough. It's the sort of thing that is not very portable, and arguably that people shouldn't be doing anyway (but probably someone does)

**Comment by toddr** [comment]
> That said, not passing on LINKTYPE may be a better solution.

@Leont To move this forward, would you be up for providing the alternative pull request?

**Comment by toddr** [comment]
> That said, not passing on LINKTYPE may be a better solution.

@Leont To move this forward, would you be up for providing the alternative pull request?

OR: Can we merge this and you provide the alternative when it is available?

**Comment by Leont** [comment]
> @Leont To move this forward, would you be up for providing the alternative pull request?

> OR: Can we merge this and you provide the alternative when it is available?

Changing this is [trivial](https://metacpan.org/release/ExtUtils-MakeMaker/source/lib/ExtUtils/MM_Unix.pm#L3068), but I haven't figured out if anything would break. I can't think of anything, but this is MakeMaker we're talking about…

**Comment by toddr** [comment]
> Changing this is [trivial](https://metacpan.org/release/ExtUtils-MakeMaker/source/lib/ExtUtils/MM_Unix.pm#L3068), but I haven't figured out if anything would break. I can't think of anything, but this is MakeMaker we're talking about…

And while it's critical, we also get feedback really fast when it breaks something. Given we've thought about it for 4 years. maybe the best option at this point is to try your suggestion and get feedback?

**Comment by xsawyerx** [comment]
> > Changing this is [trivial](https://metacpan.org/release/ExtUtils-MakeMaker/source/lib/ExtUtils/MM_Unix.pm#L3068), but I haven't figured out if anything would break. I can't think of anything, but this is MakeMaker we're talking about…
> 
> And while it's critical, we also get feedback really fast when it breaks something. Given we've thought about it for 4 years. maybe the best option at this point is to try your suggestion and get feedback?

I was going to respond with a similar question. Would it not be useful to put in the suggestion solution and try to receive feedback?

**Pull request merged**
