### PR TITLE
Add -rpath when compiling XS modules on macOS

### PR DESCRIPTION
**Pull request by hakonhagland**
This change fixes issue #402 on my machine.

### CODE REVIEW

**Comment by Leont** [comment]
Can you please change the commit title to something that actually describe what it does?

**Comment by hakonhagland** [comment]
@Leont I have updated the title to something more descriptive.

**Comment by haarg** [comment]
The important thing to fix is the subject of the actual commit, not the title of the PR.

**Comment by hakonhagland** [comment]
@haarg I have update the commit message with the same title

**Review by mohawk2 — APPROVED** [review]
Looks good to me, and the CI likes it.

**Comment by mohawk2** [comment]
@hakonhagland Could you add a test that breaks on MacOS without this change? That way we can permanently capture the benefit.

**Pull request merged**
