### PR TITLE
Teach libscan() to exclude README.pod.

### PR DESCRIPTION
**Pull request by FGasper**
This fixes issue #119.

### CODE REVIEW

**Comment by karenetheridge** [comment]
let's not be in a hurry to merge this. I'm not quite convinced yet it's the right action to take.

**Comment by FGasper** [comment]
@karenetheridge Caution is certainly reasonable, but I’m also curious as to why this has lain unresolved for so long. Is there some workaround, or is just no one putting README.pod into their distros?

My own workaround, for IO::Framed and IO::SigGuard, was to hacky-mock libscan() to reject README.pod.

Without that, because my team converts all installed Perl modules to RPMs, we actually couldn’t install those two modules concurrently because of this bug.

TBH, I’m not wild about the fix I’ve submitted, but it at least constrains the scope to the very specific problem as reported and as appears to have affected several distributions.

**Comment by FGasper** [comment]
@karenetheridge Is there something I can do to follow up on your concern?

**Comment by karenetheridge** [comment]
> is just no one putting README.pod into their distros?

Definitely not; the problem does still exist in the wild. Many tickets have been filed though and some distributions have been cleaned up.

Is it possible for the RPM creation process to filter these files out?

**Comment by FGasper** [comment]
@karenetheridge The RPM process can definitely filter out `/README.pod`, but that takes discovery of the issue each time, and each person who makes a CPAN RPM then will have to learn about this issue and its resolution. Meanwhile, each distro that wants to avoid it has to implement its own workaround. It would seem better for everyone if EU::MM were fixed.

I totally agree with erring on the side of caution for such a critical piece of the toolchain, but I’d also really like to see this fixed. :)

**Comment by karenetheridge** [comment]
I mean, can't the RPM process itself always filter out README.pod?  What scripts are being used here? We can modify those.

**Comment by FGasper** [comment]
I believe it’s a home-grown CPAN-to-RPM toolchain. (It’s not of my authorship, but I can ask.) Yeah, we can accommodate it, but someone on this end is going to ask, “well, why doesn’t EU::MM just fix its bug rather than having us accommodate it?”

Is it that the stakes for changing EU::MM are too high to warrant fixing this?

**Comment by Grinnz** [comment]
I would say that 1. the stakes for changing anything in EUMM are extremely high, and 2. the payoff for changing things in EUMM usually does not apply to the majority of perl users who will still be using old versions of EUMM for years to come. That said I think this is worth cleaning up, as README.pod inclusion is a very common bug and there's really no way for users to know this is a problem until they're told about it.

**Comment by toddr** [comment]
> I would say that 1. the stakes for changing anything in EUMM are extremely high, and 2. the payoff for changing things in EUMM usually does not apply to the majority of perl users who will still be using old versions of EUMM for years to come. 

I always have trouble with this argument. If you're saying nobody is going to use the new EU::MM for quite some time, you can't say the stakes are as high :)

My question would be what is the risk of applying the suggested patch? What could break?

**Comment by Grinnz** [comment]
> I always have trouble with this argument. If you're saying nobody is going to use the new EU::MM for quite some time, you can't say the stakes are as high :)

I did not say nobody would use it; many people use new EU::MM versions as soon as they come out, as evidenced by everything that broke in 7.12.

**Comment by bingos** [comment]
I am happy to merge this as a special case, as from #119 it seems to be affecting a lot of distributions

**Comment by Leont** [comment]
> the stakes for changing anything in EUMM are extremely high

If someone genuinely has a `Foo::Readme` module and splits his documentation from his code, this would indeed break. I'm fine with a root `Readme.pod` being skipped, but I don't think it should be skipped elsewhere (`lib/` in particular), which I think this code would do.

> I always have trouble with this argument. If you're saying nobody is going to use the new EU::MM for quite some time, you can't say the stakes are as high :)

Yeah. The actual logic is the other way around: you should assume a lot of people won't upgrade. It means that CPAN authors should still not put a `README.pod` in the root directory. Being loud about having to skip this is probably a good idea.

**Comment by sshaw** [comment]
I just finally used a modern version of ExtUtils::MakeMaker and saw this warning.  I wonder if this only became an problem because people started adding `README.pod`s for their code's GitHub page to their distro? At least that's when I started to notice it. 

Anyways, I have `README.*` in my `INSTALL.SKIP`. Seems that in this case the warning should not be generated?

**Pull request merged**
