### PR TITLE
Override shebang with PERL_MM_SHEBANG=relocatable

### PR DESCRIPTION
**Pull request by sjn**
- Relocatable shebangs are nice. Let's try to make them happen!
- This PR is related to tickets #38 and #58

### CODE REVIEW

**Comment by mohawk2** [comment]
Agreed, @sjn could you PR some docs?

**Comment by haarg** [comment]
It's not clear to me why this is a separate environment variable rather than part of the normal EUMM options.

**Comment by sjn** [comment]
@haarg: do you have a suggestion for a meaningful name? I was thinking of PERL_MM_OPT, PERL_MM_USE_DEFAULT when I picked this. Maybe "PERL_MM_FORCE_SHEBANG"?

@mohawk2, @Leont: Not entirely sure where documentation for this feature is naturally belongs... ExtUtils::MM_Unix's fixin() docs, or ExtUtils::MakeMaker's ENVIRONMENT section? Both?

**Comment by haarg** [comment]
I think it should be just a parameter given to Makefile.PL.  Like `perl Makefile.PL SHEBANG=relocatable` or `export PERL_MM_OPT="SHEBANG=relocatable"`.  It shouldn't be a separate environment variable.

**Comment by sjn** [comment]
@haarg: Ah, sorry, I misunderstood you. I assumed you didn't like the name. :smile:.

Personally I made this PR just to get the issue moving forward. It's been in limbo for FAR too long.
I chose an environment variable for this just because it was the smallest change possible to get something working.

I'll gladly try to throw in an attempt at this, but if I can have some assistance at writing tests, I'd be very happy. :grin:.

**Comment by sjn** [comment]
@haarg: Ah, sorry, I misunderstood you. I assumed you didn't like the name. :smile:.

Personally I made this PR just to get the issue moving forward. It's been in limbo for FAR too long.
I chose an environment variable for this just because it was the smallest change possible to get something working.

I'll gladly try to throw in an attempt at using EUMM options, but if I can have some assistance at writing tests, I'd be very happy. :grin:.

**Comment by mohawk2** [comment]
My feeling is that an environment variable is the wrong way to control this, but I'm not sure what's the right way. Perhaps a step towards figuring out the right way is to understand what problem we're really trying to solve.

It seems to me that installing a script with `env` in its shebang means it can fail if the wrong `perl` is first in its path. This sort of implies that maybe EUMM should instead forbid and override `env` shebangs, because that would guarantee runnable installed scripts. To try to bring this to being a single yes/no question: is there a situation where the `env` shebang is actively a good idea?

**Comment by sjn** [comment]
Well, since EUMM does everything useful through the Makefiles it generates, I'd say that using environment variables is *well* within expectations for getting shit done. :smile: .

It's a bit of a kludge to make it work through the regular EUMM options (I'm not familiar with the code), but I'll take a stab at it when I find some tuits.

**Pull request merged**
