### PR TITLE
Prefer stringify() to normal()

### PR DESCRIPTION
**Pull request by JohnPeacock**
More of the same.

### CODE REVIEW

**Comment by Leont** [comment]
@dagolden pointed out this is problematic as it can result in a non-valid version in the meta-data. Quite possibly we should revert this.

**Comment by mohawk2** [comment]
I applied it after you said you thought it was a good idea. If you're changing your mind, feel free to revert it, but I'd suggest a fuller discussion on #toolchain.

**Comment by karenetheridge** [comment]
Whatever happens, I think we need more tests of normal and weird versions
to be sure of the behaviour going forward.

**Comment by JohnPeacock** [comment]
On 01/28/2015 12:21 AM, Karen Etheridge wrote:
> Whatever happens, I think we need more tests of normal and weird versions
> to be sure of the behaviour going forward.

I thought it was a good idea too, obviously, but David is right.  I need 
to fix the alpha->normal behavior for real and haven't had a second to 
look at it since this all went down.

John

**Pull request merged**
